//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.MusicSheetDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionBase", Namespace="http://schemas.datacontract.org/2004/07/Interfaces.Database")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.MusicSheetDataService.MusicSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.MusicSheetDataService.Tag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.MusicSheetDataService.MusicSheet))]
    public partial class CollectionBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FriendlyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.MusicSheetDataService.BsonObjectId IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyId {
            get {
                return this.FriendlyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendlyIdField, value) != true)) {
                    this.FriendlyIdField = value;
                    this.RaisePropertyChanged("FriendlyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.MusicSheetDataService.BsonObjectId Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BsonObjectId", Namespace="http://schemas.datacontract.org/2004/07/MongoDB.Bson")]
    [System.SerializableAttribute()]
    public partial class BsonObjectId : Client.MusicSheetDataService.BsonValue {
        
        private Client.MusicSheetDataService.ObjectId valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Client.MusicSheetDataService.ObjectId value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusicSection", Namespace="http://schemas.datacontract.org/2004/07/Objects.Database")]
    [System.SerializableAttribute()]
    public partial class MusicSection : Client.MusicSheetDataService.CollectionBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tag", Namespace="http://schemas.datacontract.org/2004/07/Objects.Database")]
    [System.SerializableAttribute()]
    public partial class Tag : Client.MusicSheetDataService.CollectionBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusicSheet", Namespace="http://schemas.datacontract.org/2004/07/Objects.Database")]
    [System.SerializableAttribute()]
    public partial class MusicSheet : Client.MusicSheetDataService.CollectionBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComposerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.MusicSheetDataService.MusicSection[] InstrumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.MusicSheetDataService.Tag[] TagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Composer {
            get {
                return this.ComposerField;
            }
            set {
                if ((object.ReferenceEquals(this.ComposerField, value) != true)) {
                    this.ComposerField = value;
                    this.RaisePropertyChanged("Composer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.MusicSheetDataService.MusicSection[] Instruments {
            get {
                return this.InstrumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstrumentsField, value) != true)) {
                    this.InstrumentsField = value;
                    this.RaisePropertyChanged("Instruments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.MusicSheetDataService.Tag[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BsonValue", Namespace="http://schemas.datacontract.org/2004/07/MongoDB.Bson")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.MusicSheetDataService.BsonObjectId))]
    public partial class BsonValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Client.MusicSheetDataService.BsonType bsonTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Client.MusicSheetDataService.BsonType bsonType {
            get {
                return this.bsonTypeField;
            }
            set {
                if ((this.bsonTypeField.Equals(value) != true)) {
                    this.bsonTypeField = value;
                    this.RaisePropertyChanged("bsonType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BsonType", Namespace="http://schemas.datacontract.org/2004/07/MongoDB.Bson")]
    public enum BsonType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndOfDocument = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Document = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Array = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Binary = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ObjectId = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boolean = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Null = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegularExpression = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JavaScript = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Symbol = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JavaScriptWithScope = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int32 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Timestamp = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int64 = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MinKey = 255,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaxKey = 127,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectId", Namespace="http://schemas.datacontract.org/2004/07/MongoDB.Bson")]
    [System.SerializableAttribute()]
    public partial struct ObjectId : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int incrementField;
        
        private int machineField;
        
        private short pidField;
        
        private int timestampField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int increment {
            get {
                return this.incrementField;
            }
            set {
                if ((this.incrementField.Equals(value) != true)) {
                    this.incrementField = value;
                    this.RaisePropertyChanged("increment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int machine {
            get {
                return this.machineField;
            }
            set {
                if ((this.machineField.Equals(value) != true)) {
                    this.machineField = value;
                    this.RaisePropertyChanged("machine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short pid {
            get {
                return this.pidField;
            }
            set {
                if ((this.pidField.Equals(value) != true)) {
                    this.pidField = value;
                    this.RaisePropertyChanged("pid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int timestamp {
            get {
                return this.timestampField;
            }
            set {
                if ((this.timestampField.Equals(value) != true)) {
                    this.timestampField = value;
                    this.RaisePropertyChanged("timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusicSheetDataService.IMusicSheetDataService")]
    public interface IMusicSheetDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicSheetDataService/GetMusicSheet", ReplyAction="http://tempuri.org/IMusicSheetDataService/GetMusicSheetResponse")]
        Client.MusicSheetDataService.MusicSheet GetMusicSheet(string friendlyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicSheetDataService/InsertMusicSheet", ReplyAction="http://tempuri.org/IMusicSheetDataService/InsertMusicSheetResponse")]
        void InsertMusicSheet(Client.MusicSheetDataService.MusicSheet sheet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMusicSheetDataServiceChannel : Client.MusicSheetDataService.IMusicSheetDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusicSheetDataServiceClient : System.ServiceModel.ClientBase<Client.MusicSheetDataService.IMusicSheetDataService>, Client.MusicSheetDataService.IMusicSheetDataService {
        
        public MusicSheetDataServiceClient() {
        }
        
        public MusicSheetDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusicSheetDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicSheetDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicSheetDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.MusicSheetDataService.MusicSheet GetMusicSheet(string friendlyId) {
            return base.Channel.GetMusicSheet(friendlyId);
        }
        
        public void InsertMusicSheet(Client.MusicSheetDataService.MusicSheet sheet) {
            base.Channel.InsertMusicSheet(sheet);
        }
    }
}
